#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control kde
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-settings.install \
    > ./debian/${CODENAME_SAFE}-kde-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-settings.postinst \
    > ./debian/${CODENAME_SAFE}-kde-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-livesettings.install \
    > ./debian/${CODENAME_SAFE}-kde-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-kde-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-kde-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-kde-livesettings.service \
    > ./debian/${CODENAME_SAFE}-kde-livesettings.service

## templating

[ -d "./etc" ] && rm -rf ./etc
[ -d "./live" ] && rm -rf ./live
[ -d "./org.${CODENAME_SAFE}.desktop" ] && rm -rf org.${CODENAME_SAFE}.desktop

cp -a ../template/etc .

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DESCRIPTION\@/${DESCRIPTION}/g" \
    ../template/etc/xdg/kdeglobals \
    > ./etc/xdg/kdeglobals

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DESCRIPTION\@/${DESCRIPTION}/g" \
    ../template/etc/xdg/ksplashrc \
    > etc/xdg/ksplashrc



cp -a ../template/kde-cheatcodes .
cp -a ../template/kde-settings.js .

rm -rf ./live
cp -a ../template/live .
rm -rf ./usr
cp -a ../template/usr .

## hacking the look-and-feel
cp -a ../template/org.${CODENAME_SAFE}.desktop ./org.${CODENAME_SAFE}.desktop

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DESCRIPTION\@/${DESCRIPTION}/g" \
    ../template/org.${CODENAME_SAFE}.desktop/contents/defaults \
    > ./org.${CODENAME_SAFE}.desktop/contents/defaults

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/org.${CODENAME_SAFE}.desktop/metadata.desktop \
    > ./org.${CODENAME_SAFE}.desktop/metadata.desktop

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/org.${CODENAME_SAFE}.desktop/contents/loginmanager/metadata.desktop \
    > ./org.${CODENAME_SAFE}.desktop/contents/loginmanager/metadata.desktop

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/etc/skel/config/plasma-org.kde.plasma.desktop-appletsrc \
    > ./etc/skel/config/plasma-org.kde.plasma.desktop-appletsrc


# hack look-and-feel background
cp artwork/background.png \
   org.${CODENAME_SAFE}.desktop/contents/components/artwork/

grub_template kde


exit 0
