[Autologin]
Relogin=false
Session=plasmax11
User=siducer

[General]
HaltCommand=/bin/systemctl poweroff
RebootCommand=/bin/systemctl reboot
InputMethod=

[Theme]
Current=shine-on

[Users]
MaximumUid=60000
MinimumUid=1000
