#!/bin/sh
# postinst script for #PACKAGE#

set -e

case "$1" in
    configure)
        ## dconf ##
        cp -af /usr/share/wintersky-kde-settings/etc/dconf          /etc
        ## gtk-2.0 ##
        cp -af /usr/share/wintersky-kde-settings/etc/gtk-2.0          /etc
        ## kde ##
        cp -af /usr/share/wintersky-kde-settings/etc/kde-user-profile /etc
        ## policyḱit-1 ##
        cp -af /usr/share/wintersky-kde-settings/etc/polkit-1         /etc
        ## NetworkManager ##
        cp -af /usr/share/wintersky-kde-settings/etc/NetworkManager           /etc
        ## iwd ##
        cp -af /usr/share/wintersky-kde-settings/etc/iwd                      /etc
        ## skel ##
        cp -af /usr/share/wintersky-kde-settings/etc/skel/dmrc        /etc/skel/.dmrc
        cp -af /usr/share/wintersky-kde-settings/etc/skel/config      /etc/skel/.config
        cp -af /usr/share/wintersky-kde-settings/etc/skel/local       /etc/skel/.local
        ## usr ##
        cp -af /usr/share/wintersky-kde-settings/usr/*                /usr
        ## xdg ##
        cp -af /usr/share/wintersky-kde-settings/etc/xdg              /etc
        ## settings ##
        dconf update
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
